server:
  bind: "127.0.0.1:4000"
  url: "http://127.0.0.1:4000"

  cors:
    allowed-origins:
      - "http://127.0.0.1:5000"
      - "http://localhost:5000"

  session:
    cookie:
      domain: "localhost:5000"
      secure: false
      same-site: "default"

file-areas:
  - id: "tmp"
    name: "tmp"
    path: "/tmp"

users:
  - username: "demo"
    password-clear: "demo"
